Change property name so that api key is correct
companieshouse/officer-delta-processor pull request #53
Opened 2021-11-10 16:19 UTC by HarryBosworth

Spring property sources favour environment variables over properties files leading to the property `api.key` being set to `${API_KEY}` instead of using the property file which set the property to `${INTERNAL_API_KEY}`. This PR renames the property to `internal.api.key` so it is populated from the correct environment variable.

2021-11-10 16:32 UTC, divya051988 approved these changes

2021-11-11 07:36 UTC, PhilipGlover commented on src/main/resources/application.properties
> +chs.internal.api.key=${CHS_INTERNAL_API_KEY}
we need a corresponding amendment to the compose file in `docker-chs` yeah?

2021-11-11 08:01 UTC, PhilipGlover requested changes
`OfficerDeltaProcessorApplicationTests` fails "Error creating bean with name 'deltaProcessor'"

2021-11-11 08:11 UTC, PhilipGlover commented on src/main/resources/application.properties
> +chs.internal.api.key=${CHS_INTERNAL_API_KEY}
done with https://github.com/companieshouse/docker-chs-development/pull/351

2021-11-11 09:15 UTC, PhilipGlover approved these changes
have run successfully, tests pass, looking good.

2021-11-11 09:33 UTC, merged