DSND-2062 Remove empty objects during transformation
companieshouse/officer-delta-processor pull request #85
Opened 2023-09-29 10:12 UTC by cgregoryCH

* Removes any objects which contain only null fields before sending PUT request to company appointments API.

[DSND-2062](https://companieshouse.atlassian.net/browse/DSND-2062)

2023-09-29 10:15 UTC, kinpang-CH approved these changes

2023-09-29 10:47 UTC, sthompsonCH approved these changes

2023-09-29 12:22 UTC, johncook-ch requested changes

2023-09-29 12:22 UTC, johncook-ch commented on src/main/java/uk/gov/companieshouse/officer/delta/processor/tranformer/Transformative.java
> +        T target = transform(source, factory());
The return from `factory()` could be a `final` on the class initialised in the constructor. A minor improvement but...

2023-09-29 13:41 UTC, crowlandsCH approved these changes

2023-10-02 15:42 UTC, johncook-ch approved these changes

2023-10-02 17:07 UTC, merged